version: '3'

services:

  db:
    container_name: dlfproject-db
    image: mysql:8.0
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dlfproject-db
      MYSQL_ROOT_PASSWORD: root

  # api: 
  #   depends_on: 
  #     - db
  #   command: sh -c "/wait && /sayhello"
  #   container_name: dlfproject-api
  #   image: dlfproject-api
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - WAIT_HOSTS=mysql:3306
  #     - WAIT_HOSTS_TIMEOUT=300
  #     - WAIT_SLEEP_INTERVAL=30
  #     - WAIT_HOST_CONNECT_TIMEOUT=300
